---

- name: provision
  hosts: ofn_servers
  strategy: free
  remote_user: "{{ user }}"

  pre_tasks:
    - include_role:
        name: check_secrets

  handlers:
    - include: ../roles/shared_handlers/handlers/main.yml

  roles:
    - role: ssh_keys # Add sysadmin ssh keys to server
      become: yes
      tags: ssh_keys

    - role: geerlingguy.security
      become: yes
      become_user: root
      tags: security

    - role: oefenweb.swapfile
      become: yes
      tags: swapfile

    - role: app_user # Create unprivileged user to run the app
      tags: app_user

    - role: common # Install common apps and libraries, and setup shell.
      tags: common

    - role: compatibility # Handle version-specific OS dependencies and configuration
      tags: compatibility

    - role: language # Setup locale.
      tags: language

    - role: zzet.rbenv # Install ruby. If missing run: ansible-galaxy install zzet.rbenv
      rbenv:
        env: user
        version: v1.0.0
        default_ruby: "{{ ruby_version }}"
        rubies: "{{ ruby_versions }}"
      rbenv_set_vars: false
      rbenv_users:
        - "{{ app_user }}"
      tags: ruby

    - role: app # Build the app directory structure and support files.
      become: yes
      become_user: "{{ app_user }}"
      tags: app

    - role: node # Set up node and yarn with nodenv.
      become: yes
      become_user: "{{ app_user }}"
      tags: node

    - role: dbserver # Set up database server and user for the app.
      become: yes
      become_user: root
      tags: dbserver

    - role: postgres_tuning
      tags: postgres_tuning

    - role: libre_ops.multi_redis
      vars:
        multiredis_disable_default_instance: false
      become: yes
      become_user: root
      tags: redis

    - role: sidekiq
      tags: sidekiq

    - role: coopdevs.certbot_nginx
      become: yes
      vars:
        domain_name: "{{ certbot_domains | default([domain]) | join(',') }}"
        domains: "{{ certbot_domains | default([domain]) }}"
        letsencrypt_email: "{{ developer_email }}"
        certbot_nginx_cert_name: "{{ certbot_cert_name | default(domain) }}"
        certbot_version: "0.31.0-2~deb10u1+ubuntu{{ ansible_distribution_version }}.1+certbot+3"
      when: inventory_hostname not in groups['local']
      tags: certbot

    - role: brotli_nginx
      tags: brotli

    - role: jdauphant.nginx
      become: yes
      tags: nginx

    - role: webserver
      tags: webserver

    - role: datadog
      become: yes
      tags: datadog

    - role: arillso.logrotate
      become: yes
      tags: logrotate

  tasks:
    - name: Fix Ruby # noqa 301
      command:
        cmd: bash -lc "rbenv uninstall -f {{ ruby_version }} && rbenv install {{ ruby_version }} && touch ~/.rbenv/versions/{{ ruby_version }}/.reinstalled"
        creates: "~/.rbenv/versions/{{ ruby_version }}/.reinstalled"
      become: yes
      become_user: "{{ app_user }}"
      when: ansible_distribution_major_version >= '20'

    - meta: flush_handlers # Ensure handlers run successfully before reporting success

    - name: notify slack
      slack:
        token: "T02G54U79/BF25P9F7A/DJdtYaLLUpRJPiu72d8NqgGg"
        msg: '{{ inventory_hostname }} provisioned'
        channel: "#devops-notifications"
        username: "ansible executed by {{ lookup('env','USER') }}"
      when: inventory_hostname not in groups['local']

    - name: notify datadog
      uri:
        url: "https://api.datadoghq.com/api/v1/events?api_key={{ datadog_key }}"
        method: POST
        body:
          title: "Provisioned"
          text: "Provisioned host: {{ inventory_hostname }} ({{ host_id | default(ansible_limit) }})"
          host: "{{ inventory_hostname }}"
          tags:
            - "provisioned"
        body_format: json
        status_code: 202
        headers:
          Content-Type: "application/json"
      when: datadog_key is defined and inventory_hostname not in groups['local']
